version: '2'
services:
  someapp-app:
    image: someapp
    environment:
      - _JAVA_OPTIONS=-Xmx512m -Xms256m
      - MICRONAUT_ENVIRONMENTS=prod
      - JDBC_URL=jdbc:mysql://someapp-mysql:3306/someapp?useUnicode=true&characterEncoding=utf8&useSSL=false&useLegacyDatetimeCode=false&serverTimezone=UTC&createDatabaseIfNotExist=true
      - JDBC_PASSWORD=password
      - MICRONAUT_SECURITY_OAUTH2_CLIENTS_OIDC_OPENID_ISSUER=http://keycloak:9080/auth/realms/jhipster
      - MICRONAUT_SECURITY_OAUTH2_CLIENTS_OIDC_CLIENT_ID=web_app
      - MICRONAUT_SECURITY_OAUTH2_CLIENTS_OIDC_CLIENT_SECRET=web_app
      - JHIPSTER_SLEEP=30 # gives time for other services to boot before the application
    ports:
      - 8080:8080
  someapp-mysql:
    extends:
      file: mysql.yml
      service: someapp-mysql
  keycloak:
    extends:
      file: keycloak.yml
      service: keycloak
